//go:build linux

package cmd

import (
	"bytes"
	"io"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

// captureRun executes an isolated cobra command tree with the given args
// and returns the (possibly partial) stdout output. Errors are intentionally
// not asserted here — these tests assert structural properties of the tree,
// not user-facing behaviour.
func captureRun(t *testing.T, args []string) string {
	t.Helper()
	buf := &bytes.Buffer{}
	root := NewRoot()
	root.SetOut(buf)
	root.SetErr(buf)
	root.SetArgs(args)
	// Use a fresh log.Default pointer so logger config persists between
	// tests (but does not leak into the global package default).
	_ = io.Discard
	if err := root.Execute(); err != nil {
		// Most commands will exit non-zero when missing args. We only
		// want to test the help/usage path, so swallow the error.
		_ = err
	}
	return buf.String()
}

func TestNewRoot_HasPersistentGitlobals(t *testing.T) {
	root := NewRoot()
	for _, name := range []string{"log-level", "json", "quiet"} {
		if root.PersistentFlags().Lookup(name) == nil {
			t.Errorf("root command is missing persistent flag --%s", name)
		}
	}
}

func TestNewRoot_HasVersionAndName(t *testing.T) {
	root := NewRoot()
	if root.Name() != "dck" {
		t.Errorf("root name = %q; want %q", root.Name(), "dck")
	}
	if root.Version == "" {
		t.Errorf("root has empty version string")
	}
}

func TestNewRoot_RegistersAllExpectedCommands(t *testing.T) {
	root := NewRoot()
	want := []string{
		"pull", "push", "images", "verify", "search", "rmi", "commit", "build",
		"export", "run", "start", "stop", "restart", "rm", "rename", "set",
		"ps", "inspect", "logs", "stats", "top", "info",
		"exec", "console", "console-serve", "attach",
		"fs", "cp",
		"port", "network", "login", "logout", "events",
		"backup", "up", "down", "blueprint", "service", "cluster", "fn",
		"doctor", "security", "serve", "supervisor", "bootstrap", "update",
		"version", "volume", "system", "init", "registry", "import",
	}
	registered := map[string]bool{}
	for _, c := range root.Commands() {
		registered[c.Name()] = true
	}
	for _, name := range want {
		if !registered[name] {
			t.Errorf("root command tree is missing %q", name)
		}
	}
}

func TestNewRoot_BackupHasSubcommands(t *testing.T) {
	root := NewRoot()
	backup := findRootSub(root, "backup")
	if backup == nil {
		t.Fatal("backup command missing")
	}
	want := []string{"create", "list", "restore", "enable", "disable", "status", "verify"}
	for _, sub := range backup.Commands() {
		_ = sub
	}
	have := map[string]bool{}
	for _, sub := range backup.Commands() {
		have[sub.Name()] = true
	}
	for _, name := range want {
		if !have[name] {
			t.Errorf("backup command is missing subcommand %q", name)
		}
	}
}

func TestNewRoot_SecurityHasCheckSubcommand(t *testing.T) {
	root := NewRoot()
	sec := findRootSub(root, "security")
	if sec == nil {
		t.Fatal("security command missing")
	}
	var ok bool
	for _, sub := range sec.Commands() {
		if sub.Name() == "check" {
			ok = true
			break
		}
	}
	if !ok {
		t.Errorf("security command is missing `check` subcommand")
	}
}

func TestNewRoot_CompletionSubcommandExists(t *testing.T) {
	root := NewRoot()
	// `completion` is generated by cobra when the root command is
	// either executed once or has InitDefaultCompletionCmd() called.
	// Tests that only inspect the tree may not have triggered that
	// lazy registration yet, so we call it explicitly here.
	root.InitDefaultCompletionCmd()
	var ok bool
	for _, sub := range root.Commands() {
		if sub.Name() == "completion" {
			ok = true
		}
	}
	if !ok {
		t.Errorf("cobra root is missing `completion` subcommand (need cobra v1.1+)")
	}
}

// TestRunCommand_DisablesFlagParsing is a regression guard. The `run`
// command sets DisableFlagParsing because every run-level flag (--rm,
// --network, --memory, --cap-add, etc.) is parsed by the legacy
// stdlib flag.NewFlagSet inside Run() rather than by cobra itself.
// Without DisableFlagParsing, cobra would reject every run invocation
// with `unknown flag: --rm`. If you migrate run-level flags into cobra,
// flip this assertion.
func TestRunCommand_DisablesFlagParsing(t *testing.T) {
	root := NewRoot()
	run := findRootSub(root, "run")
	if run == nil {
		t.Fatal("run command missing")
	}
	if !run.DisableFlagParsing {
		t.Errorf("run.DisableFlagParsing = false; want true (legacy flag parsing)")
	}
}

func TestLegacyFlagCommands_LongHelpDoesNotExit(t *testing.T) {
	for _, name := range []string{"run", "serve"} {
		name := name
		t.Run(name, func(t *testing.T) {
			stream := &bytes.Buffer{}
			root := NewRoot()
			root.SetArgs([]string{name, "--help"})
			root.SetOut(stream)
			root.SetErr(stream)

			if err := root.Execute(); err != nil {
				t.Fatalf("%s --help returned an error: %v", name, err)
			}
			if !strings.Contains(stream.String(), name) {
				t.Fatalf("%s --help did not include the command name: %q", name, stream.String())
			}
		})
	}
}

func TestNewRoot_HelpStringContainsSubcommandSplash(t *testing.T) {
	out := captureRun(t, []string{"--help"})
	if !strings.Contains(out, "Lightweight Linux container runtime") {
		t.Errorf("help text is missing tagline: %q", out)
	}
	if !strings.Contains(out, "Available Commands") {
		t.Errorf("help text is missing auto-generated command list: %q", out)
	}
}

func TestApplyLogOptions_AcceptsAllValidLevels(t *testing.T) {
	for _, lvl := range []string{"debug", "info", "warn", "warning", "error", "err", "unknown"} {
		applyLogOptions(lvl, false, false)
	}
	// No panic means parameters were accepted.
}

// findRootSub returns the first sub-command with the given name, or nil
// if absent. It mirrors cobra's own root.Commands iterator without
// requiring the caller to inspect Children/Aliases by hand.
func findRootSub(root *cobra.Command, name string) *cobra.Command {
	for _, c := range root.Commands() {
		if c.Name() == name {
			return c
		}
	}
	return nil
}
